USE [master]
GO
/****** Object:  Database [Assesment]    Script Date: 11/6/2023 15:32:46 ******/
CREATE DATABASE [Assesment]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Assesment', SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Assesment_log', SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Assesment] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Assesment].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Assesment] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Assesment] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Assesment] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Assesment] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Assesment] SET ARITHABORT OFF 
GO
ALTER DATABASE [Assesment] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Assesment] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Assesment] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Assesment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Assesment] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Assesment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Assesment] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Assesment] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Assesment] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Assesment] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Assesment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Assesment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Assesment] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Assesment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Assesment] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Assesment] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Assesment] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Assesment] SET RECOVERY FULL 
GO
ALTER DATABASE [Assesment] SET  MULTI_USER 
GO
ALTER DATABASE [Assesment] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Assesment] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Assesment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Assesment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Assesment] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Assesment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Assesment', N'ON'
GO
ALTER DATABASE [Assesment] SET QUERY_STORE = OFF
GO
USE [Assesment]
GO
/****** Object:  Table [dbo].[_Migrations]    Script Date: 11/6/2023 15:32:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[_Migrations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Script] [varchar](500) NOT NULL,
	[CreateDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Migrations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Orders]    Script Date: 11/6/2023 15:32:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Orders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
	[Total] [money] NOT NULL,
 CONSTRAINT [PK_Orders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Products]    Script Date: 11/6/2023 15:32:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Price] [money] NOT NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Orders]  WITH CHECK ADD  CONSTRAINT [FK_Orders_Products] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Products] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Orders] CHECK CONSTRAINT [FK_Orders_Products]
GO
ALTER TABLE [dbo].[Products]  WITH CHECK ADD  CONSTRAINT [FK_Products_Products] FOREIGN KEY([Id])
REFERENCES [dbo].[Products] ([Id])
GO
ALTER TABLE [dbo].[Products] CHECK CONSTRAINT [FK_Products_Products]
GO
/****** Object:  StoredProcedure [dbo].[spCreateOrder]    Script Date: 11/6/2023 15:32:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[spCreateOrder]
	@CustomerId int,
	@ProductId int,
	@Quantity int
AS
BEGIN

	SET NOCOUNT ON;

    declare @Price int = (SELECT top 1 Price from Products where Id=@ProductId)

	INSERT INTO Orders (CustomerId,ProductId,Quantity,Total)
	VALUES (@CustomerId, @ProductId, @Quantity, @Quantity*@Price)

	SELECT @@IDENTITY

END
GO
USE [master]
GO
ALTER DATABASE [Assesment] SET  READ_WRITE 
GO
